---

- name: Create a volume {{ item.name }}
  docker_volume:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    force: "{{ item.force | default('no') }}"
    driver: "{{ item.driver | default('local') }}"
    driver_options:
      type: "{{ item.type | default('none') }}"
      device: "{{ item.paths }}"
      o: bind