---

- name: Install fail2ban
  package:
    name: fail2ban
    state: latest

- name: Configure Fail2ban
  template:
    src:   etc/fail2ban/jail.local.j2
    dest: /etc/fail2ban/jail.local
  notify: "Restart Fail2ban"
