---

- name: Set hostname based on inventory name
  hostname:
    name: "{{ inventory_hostname }}"
  when: "{{ common_do_not_set_hostname_as_inventory|bool }} == false"

- name: Add comment ansible comments in /etc/hosts
  lineinfile:
    dest=/etc/hosts
    line='# ansible managed 127.0.0.1 line'
    insertbefore='^127\.0\.0\.1.*localhost.*'
    state=present

- name: Add hostname in /etc/hosts
  lineinfile:
    dest=/etc/hosts
    regexp='^127\.0\.0\.1.*localhost'
    line='127.0.0.1 {{ inventory_hostname }} localhost'
    state=present  
