---

- name: Add/remove admin users
  when: users_admins is defined and users_admins and not users_root_keys
  user:
    name: "{{ item.username }}"
    state: "{{ item.state }}"
    force: yes
    remove: yes
    system: no
    createhome: yes
    groups: "adm,sudo"
    append: yes
    shell: /bin/bash

- name: Fix perm. for homedir
  file:
    path: /home/{{ item.username }}
    state: directory
    mode: 0750
